export enum CourseDuration {
  COURSE_DURATION1 = "COURSE_DURATION1",
  COURSE_DURATION2 = "COURSE_DURATION2",
  COURSE_DURATION3 = "COURSE_DURATION3",
  COURSE_DURATION4 = "COURSE_DURATION4",
  COURSE_DURATION5 = "COURSE_DURATION5",
  COURSE_DURATION6 = "COURSE_DURATION6"
}
