export const AppRoutes = {
  home: "/",
  teacherLanding: "/teacher",
  studentLanding: "/student",
  auth: "/auth",
  authType: "/auth/:authType",
  login: "/login",
  registration: "/registration",
  createCourse: "/create-course",
  createCourseLanding: "/create-course/landing",
  createCourseStructure: "/create-course/structure",
  createCourseLecturer: "/create-course/lecturer",
  createCoursePrice: "/create-course/price",
  createCourseAdvertising: "/create-course/advertising",
  authType: "/auth/:authType/:role",
  authTypeLogin: "/auth/login",
  authTypeRegistration: "/auth/registration",
  authRoles: "/auth/roles",
  createCourse: "/create-сourse",
  previewCourse: "/course/:courseId",
  notFound: "*",
  ui: "/ui",
  myCourses: "/my-courses",
  helpCenter: "/help-center",
  statistic: "/statistic",
  account_verification: "/account-verification",
  email_update: "/email-update",
  password_update: "/password-update",
};

export enum AuthPageSection {
  LOGIN = "login",
  REGISTRATION = "registration",
}
