export const AppRoutes = {
  home: "/",
  studentLanding: "/student",

  auth: {
    base: "/auth",
    typeRole: "/auth/:authType/:role",
    roles: "/auth/roles",
    login: "/auth/login",
    registration: "/auth/registration",
    accountVerification: "/auth/account-verification",
    emailUpdate: "/auth/email-update",
    passwordUpdate: "/auth/password-update",
  },
  student: {
    dashboard: "/student/dashboard",
    profile: "/student/dashboard/profile",
    myLearning: "/student/dashboard/my-learning",
    myLearningSingle: "/student/dashboard/my-learning/:id",
    completedCourses: "/student/dashboard/completed-courses",
    certificates: "/student/dashboard/certificates",
    certificatesSingle: "/student/dashboard/certificates/:id",
    pricing: "/student/dashboard/pricing",
    support: "/student/dashboard/support",
    favoriteCourses: "/student/dashboard/favorite-courses",
  },
  teacher: {
    dashboard: "/teacher/dashboard",
    profile: "/teacher/dashboard/profile",
    myCourses: "/teacher/dashboard/my-courses",
    myCourseSingle: "/teacher/dashboard/my-courses/:id",
    statistic: "/teacher/dashboard/statistic",
    billing: "/teacher/dashboard/billing",
    support: "/teacher/dashboard/support",
    previewCourse: "/teacher/course-preview/:id",
    createCourse: "/teacher/dashboard/create-course",
    createCourseLanding: "/teacher/dashboard/create-course/landing",
    createCourseStructure: "/teacher/dashboard/create-course/structure",
    createCourseLecturer: "/teacher/dashboard/create-course/lecturer",
    createCoursePrice: "/teacher/dashboard/create-course/price",
    createCourseAdvertising: "/teacher/dashboard/create-course/advertising",
  },
  notFound: "*",
  ui: "/ui",
  helpCenter: "/help-center",
};

export enum AuthPageSection {
  LOGIN = "login",
  REGISTRATION = "registration",
}
