export * from "./authorization";
export * from "./course-preview";
export * from "./create-course";
export * from "./home-template";
export * from "./login";
export * from "./registration";
export * from "./student/landing-page";
export * from "./teacher/landing-page";
export * from "./teacher/my-courses-page";
export { default as UiPage } from "./ui";
