export * from "./auth/authorization";
export * from "./course-preview";
export * from "./create-course";
export * from "./auth/login";
export * from "./auth/registration";
export * from "./student/landing-page";
export * from "./teacher/landing-page";
export * from "./teacher/my-courses-page";
export * from "./auth/account-verification";
export * from "./auth/email-update";
export { default as UiPage } from "./ui";
